export const fontFamilies = [
  { title: "Manrope", value: "manrope" },
  { title: "Inter", value: "inter" },
  { title: "Roboto", value: "roboto" },
  { title: "Arial", value: "arial" },
  { title: "Helvetica", value: "helvetica" },
  { title: "Verdana", value: "verdana" },
  { title: "Tahoma", value: "tahoma" },
  { title: "Trebuchet MS", value: "trebuchet" },
  { title: "Georgia", value: "georgia" },
  { title: "Palatino", value: "palatino" },
  { title: "Times New Roman", value: "times" },
  { title: "Garamond", value: "garamond" },
  { title: "Courier New", value: "courier" },
  { title: "Lucida Console", value: "lucida-console" },
  { title: "Lucida Sans", value: "lucida-sans" },
  { title: "Impact", value: "impact" },
  { title: "Comic Sans MS", value: "comic-sans" },
  { title: "System UI", value: "system-ui" },
  { title: "UI Sans", value: "ui-sans" },
  { title: "UI Serif", value: "ui-serif" },
  { title: "UI Monospace", value: "ui-monospace" },
  { title: "Cursive", value: "cursive" },
] as const;

export const fontFamilyCss: Record<string, string> = {
  manrope: "var(--font-manrope), sans-serif",
  inter: "var(--font-inter), sans-serif",
  roboto: "var(--font-roboto), sans-serif",
  arial: "Arial, Helvetica, sans-serif",
  helvetica: "Helvetica, Arial, sans-serif",
  verdana: "Verdana, Geneva, sans-serif",
  tahoma: "Tahoma, Geneva, sans-serif",
  trebuchet: '"Trebuchet MS", sans-serif',
  georgia: "Georgia, serif",
  palatino: '"Palatino Linotype", "Book Antiqua", Palatino, serif',
  times: '"Times New Roman", Times, serif',
  garamond: "Garamond, serif",
  courier: '"Courier New", Courier, monospace',
  "lucida-console": '"Lucida Console", Monaco, monospace',
  "lucida-sans": '"Lucida Sans Unicode", "Lucida Grande", sans-serif',
  impact: "Impact, Charcoal, sans-serif",
  "comic-sans": '"Comic Sans MS", "Comic Sans", cursive',
  "system-ui": "system-ui, sans-serif",
  "ui-sans": "ui-sans-serif, system-ui, sans-serif",
  "ui-serif": "ui-serif, Georgia, serif",
  "ui-monospace": 'ui-monospace, "SFMono-Regular", monospace',
  cursive: "cursive",
};

export const fontSizes = [
  { title: "12 px", value: "12px" },
  { title: "14 px", value: "14px" },
  { title: "16 px", value: "16px" },
  { title: "18 px", value: "18px" },
  { title: "20 px", value: "20px" },
  { title: "22 px", value: "22px" },
  { title: "24 px", value: "24px" },
  { title: "28 px", value: "28px" },
  { title: "32 px", value: "32px" },
  { title: "36 px", value: "36px" },
  { title: "42 px", value: "42px" },
  { title: "48 px", value: "48px" },
  { title: "56 px", value: "56px" },
] as const;

export const fontWeights = [
  { title: "Light 300", value: "300" },
  { title: "Regular 400", value: "400" },
  { title: "Medium 500", value: "500" },
  { title: "Semibold 600", value: "600" },
  { title: "Bold 700", value: "700" },
  { title: "Extra bold 800", value: "800" },
] as const;
